import { calculateAnalytics, detectWeakAreas } from './analytics';

export const generateReport = (sessionData, questions) => {
    const { topic, results, startTime, endTime } = sessionData;
    const analytics = calculateAnalytics(results);
    const weakAreas = detectWeakAreas(results, questions);

    const formatDate = (date) => {
        return new Date(date).toLocaleString('en-IN', {
            day: '2-digit',
            month: 'short',
            year: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
        });
    };

    const duration = ((endTime - startTime) / 1000 / 60).toFixed(1);

    let report = `
╔══════════════════════════════════════════════════════════════╗
║                    📊 SESSION REPORT                          ║
╚══════════════════════════════════════════════════════════════╝

📅 Date: ${formatDate(startTime)}
📚 Topic: ${topic}
⏱️ Duration: ${duration} minutes

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📈 PERFORMANCE SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   Total Questions    : ${analytics.total}
   ✅ Correct          : ${analytics.correct}
   ❌ Wrong            : ${analytics.wrong}
   ⏭️ Not Attempted    : ${analytics.notAttempted}
   
   🎯 Accuracy         : ${analytics.accuracy}%
   ⚡ Average Time     : ${analytics.avgTime} sec
   🚀 Fastest Answer   : ${analytics.fastestTime} sec
   🐢 Slowest Answer   : ${analytics.slowestTime} sec

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

⚠️ WEAK AREAS (Need Revision)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`;

    if (weakAreas.length > 0) {
        weakAreas.forEach(area => {
            report += `   • ${area.topic} - ${area.accuracy}% (${area.status})\n`;
        });
    } else {
        report += `   ✨ Great job! No weak areas detected.\n`;
    }

    report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📝 DETAILED QUESTION LOG
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`;

    results.forEach((result, index) => {
        const question = questions.find(q => q.id === result.questionId);
        const statusEmoji = result.status === 'Correct' ? '✅' :
            result.status === 'Wrong' ? '❌' : '⏭️';
        const timeStr = result.status === 'Not Attempted' ?
            'Time Out' : `${result.timeTaken.toFixed(1)}s`;

        report += `Q${index + 1}. ${question?.question?.substring(0, 50)}...\n`;
        report += `    ${statusEmoji} ${result.status} | ⏱️ ${timeStr}\n`;

        if (result.status === 'Wrong') {
            report += `    Your Answer: ${String.fromCodePoint(65 + result.selectedAnswer)}\n`;
            report += `    Correct: ${String.fromCodePoint(65 + question?.correctIndex)}\n`;
        }
        report += '\n';
    });

    report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💡 RECOMMENDATIONS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

`;

    if (analytics.accuracy >= 80) {
        report += `   🌟 Excellent performance! Keep it up!\n`;
    } else if (analytics.accuracy >= 60) {
        report += `   📖 Good effort! Focus on weak areas.\n`;
    } else {
        report += `   📚 Needs improvement. Revise the basics.\n`;
    }

    if (analytics.avgTime > 8) {
        report += `   ⚡ Try to improve response time.\n`;
    }

    if (analytics.notAttempted > 0) {
        report += `   ⏰ Work on time management for unattempted questions.\n`;
    }

    report += `
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Generated by Quiz Engine 🎯
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
`;

    return report;
};

// Download report as TXT file
export const downloadReport = (reportText, topic) => {
    const blob = new Blob([reportText], { type: 'text/plain;charset=utf-8' });
    const link = document.createElement('a');
    const timestamp = new Date().toISOString().split('T')[0];

    link.href = URL.createObjectURL(blob);
    link.download = `quiz_report_${topic.replaceAll(/\s+/g, '_')}_${timestamp}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(link.href);
};
